### ISSUE TITLE
Output power not varying with WindSpeedChanging

### ISSUE THREAD

**Issue by jdelhaxhe** [Seth401/windturbines-redux#2]
With original WindSpeedChanging mod (not Tweaked)

The output power from wind turbines is constant.

See with new windturbines : 
![Capture5](https://user-images.githubusercontent.com/33958658/218570850-a3c0946a-1dcd-4414-a0be-5d8d9abbc675.JPG)

When migrating from Windturbines-2-configurable-power mod (last 10 minutes) : 
![Capture7](https://user-images.githubusercontent.com/33958658/218570863-a5bcb1cb-0de8-435e-851e-64b9259d93df.JPG)

Settings : 
![Capture6](https://user-images.githubusercontent.com/33958658/218570888-e4f21548-45ce-412d-8340-3a92605ca43f.JPG)

**Comment by Seth401** [comment]
The power output formula isn't adapted when WindSpeedChanging is being used. Merely the wind speed isn't also varied by this mod so only the variation of WindSpeedChanigng is happening. In order to fix this the power output formula would have to be adapted or at the very least the wind speed that is used within the calculation.

A simple approach would be to divide the wind speed value by 10. This isn't going to be perfect but should help bring it more inline.

**Comment by jdelhaxhe** [comment]
Seems corrected !
